// PROJECT 10 - PRESERVING DATA IN THE BROWSER

// FIRST, TAKE THE INFO FROM 3 INPUTS AN STORE IN LOCALSTORAGE (JSON).

// THEN, IF THERE IS ANY DATA IN LOCALSTORAGE, WHEN THE PAGE LOADS,
// THE INPUT FIELDS ARE PREFILLED WITH THE DATA.

// THIRD, WHEN THE USER CHANGES ANY INPUT FIELD, THE DATA IS SAVED IN
// LOCALSTORAGE
 